apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  # รหัสจริงสำหรับ K8s อยู่ที่นี่ที่เดียว
  # production: ควรสร้างด้วย `kubectl create secret` แทนการ commit ค่าจริง
  password: "27926"
